export interface App {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  category: string;
  isInstalled: boolean;
  isCore: boolean;
  route?: string;
  version: string;
  author: string;
  dependencies?: string[];
}

export const AVAILABLE_APPS: App[] = [
  // Core Business Apps
  {
    id: 'crm',
    name: 'CRM',
    description: 'Manage leads, opportunities and customers',
    icon: '💼',
    color: 'bg-blue-500',
    category: 'Sales',
    isInstalled: true,
    isCore: true,
    route: '/crm',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'sales',
    name: 'Sales',
    description: 'Manage sales orders and quotations',
    icon: '📊',
    color: 'bg-green-500',
    category: 'Sales',
    isInstalled: true,
    isCore: true,
    route: '/sales',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'inventory',
    name: 'Inventory',
    description: 'Manage products, stock and warehouses',
    icon: '📦',
    color: 'bg-orange-500',
    category: 'Inventory',
    isInstalled: false,
    isCore: true,
    route: '/inventory',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'accounting',
    name: 'Accounting',
    description: 'Manage invoices, payments and financial reports',
    icon: '💰',
    color: 'bg-yellow-500',
    category: 'Finance',
    isInstalled: false,
    isCore: true,
    route: '/accounting',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'hr',
    name: 'Human Resources',
    description: 'Manage employees, contracts and payroll',
    icon: '👥',
    color: 'bg-purple-500',
    category: 'Human Resources',
    isInstalled: false,
    isCore: true,
    route: '/hr',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'project',
    name: 'Project Management',
    description: 'Manage projects, tasks and timesheets',
    icon: '📋',
    color: 'bg-indigo-500',
    category: 'Project',
    isInstalled: false,
    isCore: true,
    route: '/project',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    description: 'Manage production orders and bill of materials',
    icon: '🏭',
    color: 'bg-gray-600',
    category: 'Manufacturing',
    isInstalled: false,
    isCore: true,
    route: '/manufacturing',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'purchase',
    name: 'Purchase',
    description: 'Manage purchase orders and vendor bills',
    icon: '🛒',
    color: 'bg-teal-500',
    category: 'Purchase',
    isInstalled: false,
    isCore: true,
    route: '/purchase',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'website',
    name: 'Website Builder',
    description: 'Create and manage your company website',
    icon: '🌐',
    color: 'bg-cyan-500',
    category: 'Website',
    isInstalled: false,
    isCore: true,
    route: '/website',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'ecommerce',
    name: 'eCommerce',
    description: 'Sell products online with integrated shop',
    icon: '🛍️',
    color: 'bg-pink-500',
    category: 'Website',
    isInstalled: false,
    isCore: true,
    route: '/ecommerce',
    version: '1.0.0',
    author: 'Core Team',
    dependencies: ['website', 'sales', 'inventory'],
  },
  {
    id: 'marketing',
    name: 'Email Marketing',
    description: 'Create and send marketing campaigns',
    icon: '📧',
    color: 'bg-red-500',
    category: 'Marketing',
    isInstalled: false,
    isCore: true,
    route: '/marketing',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'helpdesk',
    name: 'Helpdesk',
    description: 'Manage customer support tickets',
    icon: '🎧',
    color: 'bg-emerald-500',
    category: 'Services',
    isInstalled: false,
    isCore: true,
    route: '/helpdesk',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    description: 'Schedule meetings and manage events',
    icon: '📅',
    color: 'bg-violet-500',
    category: 'Productivity',
    isInstalled: false,
    isCore: true,
    route: '/calendar',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'documents',
    name: 'Documents',
    description: 'Store and organize company documents',
    icon: '📁',
    color: 'bg-slate-500',
    category: 'Productivity',
    isInstalled: false,
    isCore: true,
    route: '/documents',
    version: '1.0.0',
    author: 'Core Team',
  },
  {
    id: 'contacts',
    name: 'Contacts',
    description: 'Manage customers, vendors and partners',
    icon: '📇',
    color: 'bg-amber-500',
    category: 'Sales',
    isInstalled: true,
    isCore: true,
    route: '/contacts',
    version: '1.0.0',
    author: 'Core Team',
  },
];

export const APP_CATEGORIES = [
  'All',
  'Sales',
  'Inventory',
  'Finance',
  'Human Resources',
  'Project',
  'Manufacturing',
  'Purchase',
  'Website',
  'Marketing',
  'Services',
  'Productivity',
];
