version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: shadcn-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shadcn_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shadcn-network

  # Optional: Add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: shadcn-pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - shadcn-network

networks:
  shadcn-network:
    driver: bridge

volumes:
  postgres-data:
